GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "firstName": "Ana",
    "lastName": "Maria"
}

###

DELETE http://localhost:3000/api/users/8

###

PATCH  http://localhost:3000/api/users/2
Content-Type: application/json

{
    "firstName": "Marco Aureliano",
    "lastName": "Hansen"
}

###

GET http://localhost:3000/api/users/7

###

PATCH http://localhost:3000/api/users/8/toggle

###
GET http://localhost:3000/api/users/active
